AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - redfish_tools.gemspec
    - Gemfile
    - Rakefile
    - bin/**

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Metrics/MethodLength:
  Exclude:
    - lib/redfish_tools/cli.rb

Naming/MethodName:
  Exclude:
    - lib/redfish_tools/servlet.rb
